# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ icstlatest ]
  pull_request:
    branches: [ icstlatest ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    - name: Checkout CGSerializer
      uses: actions/checkout@v2
      with:
        repository: linghuiluo/CGSerializer
        token: 6e27591551907198dbfec46ad6d75cb441f88dff
        path: CGSerializer
    - name: Build CGSerializer
      run: |
          cd CGSerializer
          mvn install -DskipTests
          cd ..
          rm -rf CGSerializer
    - name: Check out soot
      run: |
        cd /home/runner/work/
        git clone https://github.com/soot-oss/soot.git
        cd soot
        git checkout dba4cbcc0d84f507944c6b3eaac14b82c13754fa
        mvn install -DskipTests
    - uses: actions/checkout@v2
    - name: Build FlowDroid
      run: mvn install -DskipTests
    - run: ls 
